In [3]:
# scikit-learn의 CountVectorizer를 이용하여 
# 텍스트 문장을 벡터로 구성하는 코드

# 사용 빈도수가 높은 단어가 행렬의 앞으로 놓여진다.

from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

txt1 = 'the car is expensive'
txt2 = 'the truck is cheap'
txt3 = 'the car is expensive and the truck is cheap'

count = CountVectorizer()
docs = np.array([txt1, txt2, txt3]) # 문장을 numpy 배열로 저장
bag = count.fit_transform(docs)      # txt1~txt3을 이용해 단어장 구성

print(count.vocabulary_)           # 사전자료로 구성된 단어장 출력
print(bag.toarray())                # 문장의 특성을 벡터로 구성한 내용 출력

{'expensive': 3, 'cheap': 2, 'is': 4, 'the': 5, 'car': 1, 'truck': 6, 'and': 0}
[[0 1 0 1 1 1 0]
 [0 0 1 0 1 1 1]
 [1 1 1 1 2 2 1]]
