In [1]:
import numpy as np
from mylib.Perceptron import perceptron

if __name__ == '__main__':
    X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
    y = np.array([-1, -1, -1, 1])
    
    ppn = perceptron(eta=0.1)
    ppn.fit(X, y)
    print(ppn.errors_)

[ 0.2  0.2  0.2]
[ 0.   0.4  0.2]
[-0.2  0.4  0.2]
[-0.2  0.4  0.4]
[-0.4  0.4  0.2]
[-0.4  0.4  0.2]
[-0.4  0.4  0.2]
[-0.4  0.4  0.2]
[-0.4  0.4  0.2]
[-0.4  0.4  0.2]
[1, 3, 3, 2, 1, 0, 0, 0, 0, 0]
